  import { Inter } from "next/font/google";
  import "./globals.css";

  

  export const metadata = {
    title: "GetHub Card ",
    description: "Generated by Gethub",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body >{children}</body>
      </html>
    );
  }
